# Numpy Assignment

# Question no. 1 

In [1]:
import numpy as np

In [2]:
list_ = ['1','2','3','4','5']

In [3]:
array_list = np.array(object = list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(list_)

list

Yes there is a difference in the data types of the variables "list_" and "array_list". The "list_" in Python list nad "array_list" is Numpy array.

In [6]:
print("data type of list_ :",type(array_list))

data type of list_ : <class 'numpy.ndarray'>


In [7]:
print("data type of the array_list :" ,type(list_))

data type of the array_list : <class 'list'>


# Question no. 2:

In [8]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
for j in array_list:
    print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Question no.3:

In [10]:
array_list = np.array(object = list_,dtype = int)

In [11]:
array_list

array([1, 2, 3, 4, 5])

In [12]:
for j in array_list:
    print(type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [13]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


As we can see abovethe type of List is str and the type of array_list is int so they are not same 

# Question no.4:

In [14]:
num_list = [[1,2,3] ,[4,5,6]]

In [15]:
num_array = np.array(object = num_list)

In [16]:
num_array.shape

(2, 3)

In [18]:
num_array.size

6

# Question no.5:

In [25]:
arr = np.zeros((3,3))

In [26]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Question no.6 :

In [31]:
arr1 = np.eye(5,5)

In [32]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])